config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'admin' do
    namespace :admin, path: '/' do
      root 'root#index'
      resources :community, as: :communities, controller: :communities
      resources :sailing, as: :sailings, controller: :sailings, only: [:create, :new], path: 'community/:community_id/sailing'
      resources :sailing, as: :sailings, controller: :sailings, only: [:show, :edit, :update, :destroy]
      resources :participant, as: :participants, controller: :participants, only: [:create], path: 'sailing/:sailing_id/participant'
      resources :participant, as: :participants, controller: :participants, only: [:destroy]
      resources :comment, as: :comments, controller: :comments, only: [:create, :new], path: 'sailing/:sailing_id/comment'
      resources :comment, as: :comments, controller: :comments, only: [:edit, :update, :destroy]
      resources :images
    end
  end

  get 'user/signin'

  root 'root#index'

  [ :about, :company, :terms, :privacy, :owner ].each do |key|
    get key, to: "root##{key}", as: key
  end

  post :contact, to: 'root#contact', as: :contact

  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    skip: [ :sessions, :registrations, :password ]

  devise_scope :user do
    get 'signin',  to: 'user#signin',             as: :new_user_session
    get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :participant, as: :participants, path: 'sailing/:sailing_id/participants', controller: :participants
  resources :community, as: :communities, controller: :communities, only: [:show] do
    member do
      post :interest
      post :another_time
    end
  end
  resources :member, as: :members, path: 'community/:community_id/members', controller: :members

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :sailing
  belongs_to :user

  validates :user, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than: 5 }
  validates :body, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_action :set_sailing, only: [:new, :create]
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment.sailing = @sailing
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.sailing = @sailing

    respond_to do |format|
      if @comment.save
        format.html { redirect_to admin_sailing_path(@sailing), notice: 'コメントを追加しました' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to admin_sailing_path(@comment.sailing), notice: 'コメントを保存しました' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to admin_sailing_path(@comment.sailing), notice: 'コメントを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    def set_sailing
      @sailing = Sailing.find(params[:sailing_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.fetch(:comment).permit(:user_id, :rating, :title, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.slim
- params = { html: { class: 'form-horizontal' } }
- if @comment.new_record?
  - params[:url] = admin_comments_path(sailing_id: @comment.sailing)
- else
  - params[:url] = admin_comment_path(sailing_id: @comment.sailing)
  - params[:html][:method] = 'patch'

= form_for @comment, params do |f|
  - if @comment.errors.any?
    = render 'admin/layout/form_error', errors: @comment.errors

  .form-group
    - users = @comment.sailing.not_commented_users
    - users << @comment.user unless @comment.user.blank? or users.include? @comment.user
    = f.label :user_id, '投稿ユーザー', class: 'col-sm-2 control-label'
    .col-sm-10= f.collection_select :user_id, users, :id, :name, { include_blank: true }, class: 'form-control'

  .form-group
    = f.label :rating, '評価', class: 'col-sm-2 control-label'
    .col-sm-10= f.range_field :rating, class: 'form-control', min: 0, max: 4

  .form-group
    = f.label :title, 'タイトル', class: 'col-sm-2 control-label'
    .col-sm-10= f.text_field :title, class: 'form-control', rows: 8

  .form-group
    = f.label :body, '内容', class: 'col-sm-2 control-label'
    .col-sm-10= f.text_area :body, class: 'form-control', rows: 8

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit '保存', class: 'btn btn-primary'

app/views/admin/comments/_index.html.slim
table.table.table-striped.table-bordered
  tr
    th ユーザー
    th タイトル
    th style='width: 30%' 内容
    th 評価
    th 投稿日時
    th 操作
  - comments.each do |comment|
    tr
      td= comment.user.name
      td= comment.title
      td= simple_format comment.body
      td
        - 5.times do |n|
          = if comment.rating < n then '☆' else '★'
      td= comment.created_at
      td
        = link_to '編集', edit_admin_comment_path(comment), class: 'btn btn-success btn-sm'
        = link_to '削除', admin_comment_path(comment), data: { confirm: '本当に削除しますか？' }, method: :delete, class: 'btn btn-danger btn-sm'

app/views/admin/comments/edit.html.slim
ol.breadcrumb
  li= link_to @comment.sailing.community.name, admin_community_path(@comment.sailing.community)
  li= link_to @comment.sailing.name, admin_sailing_path(@comment.sailing)
  li.active レビューを編集

h2 レビューを編集

== render 'form'

app/views/admin/comments/new.html.slim
ol.breadcrumb
  li= link_to @sailing.community.name, admin_community_path(@sailing.community)
  li= link_to @sailing.name, admin_sailing_path(@sailing)
  li.active レビューを追加

h2 レビューを追加

== render 'form'