config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'admin' do
    namespace :admin, path: '/' do
      root 'root#index'
      resources :community, as: :communities, controller: :communities
      resources :sailing, as: :sailings, controller: :sailings, only: [:create, :new], path: 'community/:community_id/sailing'
      resources :sailing, as: :sailings, controller: :sailings, only: [:show, :edit, :update, :destroy]
      resources :participant, as: :participants, controller: :participants, only: [:create], path: 'sailing/:sailing_id/participant'
      resources :participant, as: :participants, controller: :participants, only: [:destroy]
      resources :comment, as: :comments, controller: :comments, only: [:create, :new], path: 'sailing/:sailing_id/comment'
      resources :comment, as: :comments, controller: :comments, only: [:edit, :update, :destroy]
      resources :images
    end
  end

  get 'user/signin'

  root 'root#index'

  [ :about, :company, :terms, :privacy, :owner ].each do |key|
    get key, to: "root##{key}", as: key
  end

  post :contact, to: 'root#contact', as: :contact

  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    skip: [ :sessions, :registrations, :password ]

  devise_scope :user do
    get 'signin',  to: 'user#signin',             as: :new_user_session
    get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :participant, as: :participants, path: 'sailing/:sailing_id/participants', controller: :participants
  resources :community, as: :communities, controller: :communities, only: [:show] do
    member do
      post :interest
      post :another_time
    end
  end
  resources :member, as: :members, path: 'community/:community_id/members', controller: :members

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/image.rb
require 'aws-sdk'

Aws.config[:credentials] = Aws::Credentials::new ENV['S3_ACCESS_KEY_ID'], ENV['S3_SECRET_ACCESS_KEY']

class Image < ActiveRecord::Base
  belongs_to :user
  attr_accessor :file

  before_create :save_file_info
  after_create :save_file
  before_destroy :destroy_file

  validates :user, presence: true
  validates :file, presence: true, on: :create

  def save_file_info
    self.filetype = file.content_type
    self.filename = file.original_filename
    self.filesize = file.size
    self
  end

  def save_file
    s3_bucket.put_object key: self.id, body: file
    self
  end

  def destroy_file
    obj = s3_bucket.object(self.id)
    return false unless obj
    deleted_object = s3_bucket.object "deleted/#{self.id}"
    obj.move_to deleted_object
    self
  end

  def url
    ENV['IMAGE_HOST_URL'] + id
  end

  private
    def s3_bucket
      unless @_s3_bucket
        s3_client = Aws::S3::Client.new region: ENV['S3_REGION']
        @_s3_bucket = Aws::S3::Bucket.new ENV['S3_BUCKET_NAME'], client: s3_client
      end
      @_s3_bucket
    end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    images = image_params
    images[:files] = [ images[:file] ] if images[:file]

    images[:files].each do |file|
      image = Image.new({
        file: file,
        user: current_user,
        description: images[:description]
      })
      raise unless image.save
    end

    redirect_to admin_images_path, notice: 'Image was successfully created.'
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to admin_image_path(@image), notice: '画像をアップロードしました' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_images_path, notice: '画像を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:file, :filename, :description, files: [])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:file)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.slim
- form_opts = { html: { class: 'form-horizontal' } }
- if @image.new_record?
  - form_opts[:url] = admin_images_path(@image)
- else
  - form_opts[:url] = admin_image_path(@image)
  - form_opts[:html][:method] = 'patch'

= form_for @image, form_opts do |f|
  - if @image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - @image.errors.full_messages.each do |message|
          li = message

  = f.file_field :file

  .actions = f.submit

app/views/admin/images/edit.html.slim
h1 画像を編集

- form_opts = { html: { class: 'form-horizontal', method: 'patch' }, url: admin_image_path(@image) }
= form_for @image, form_opts do |f|
  - if @image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - @image.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :filename, 'ファイル名'
    = f.text_field :filename, class: 'form-control'

  .form-group
    = f.text_area :description, class: 'form-control', placeholder: '補足説明など'

  .form-group
    = f.submit '保存', class: 'btn btn-primary'

app/views/admin/images/index.html.slim
h1 画像一覧
= link_to 'アップロード', new_admin_image_path, class: 'btn btn-primary'

ul.media-list style='margin-top: 1em'
  - @images.order(created_at: :desc).each do |image|
    li.media
      .media-left
        = link_to '', admin_image_path(image), class: 'cropedImage', style: "background-image: url(#{image.url})"
      .media-body
        h4.media-heading= link_to image.filename, admin_image_path(image)
        p= image.description
        input.form-control type='text' value=image.url readonly=true

app/views/admin/images/new.html.slim
h1 画像をアップロード

- form_opts = { html: { class: 'form-horizontal' }, url: admin_images_path(@image) }
= form_for @image, form_opts do |f|
  - if @image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - @image.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.file_field :files, class: 'form-control', accept: 'image/*', multiple: true

  .form-group
    = f.text_area :description, class: 'form-control', placeholder: '補足説明など'

  .form-group
    = f.submit 'アップロード', class: 'btn btn-primary'

app/views/admin/images/show.html.slim
h1= @image.filename
p= simple_format @image.description

= link_to @image.url, class: :thumbnail, target: :_blank do
  = image_tag @image.url

= link_to '編集', edit_admin_image_path(@image), class: 'btn btn-success'
= link_to '削除', admin_image_path(@image), data: { confirm: '本当に削除しますか？' }, method: :delete, class: 'btn btn-danger'