config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'admin' do
    namespace :admin, path: '/' do
      root 'root#index'
      resources :community, as: :communities, controller: :communities
      resources :sailing, as: :sailings, controller: :sailings, only: [:create, :new], path: 'community/:community_id/sailing'
      resources :sailing, as: :sailings, controller: :sailings, only: [:show, :edit, :update, :destroy]
      resources :participant, as: :participants, controller: :participants, only: [:create], path: 'sailing/:sailing_id/participant'
      resources :participant, as: :participants, controller: :participants, only: [:destroy]
      resources :comment, as: :comments, controller: :comments, only: [:create, :new], path: 'sailing/:sailing_id/comment'
      resources :comment, as: :comments, controller: :comments, only: [:edit, :update, :destroy]
      resources :images
    end
  end

  get 'user/signin'

  root 'root#index'

  [ :about, :company, :terms, :privacy, :owner ].each do |key|
    get key, to: "root##{key}", as: key
  end

  post :contact, to: 'root#contact', as: :contact

  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    skip: [ :sessions, :registrations, :password ]

  devise_scope :user do
    get 'signin',  to: 'user#signin',             as: :new_user_session
    get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :participant, as: :participants, path: 'sailing/:sailing_id/participants', controller: :participants
  resources :community, as: :communities, controller: :communities, only: [:show] do
    member do
      post :interest
      post :another_time
    end
  end
  resources :member, as: :members, path: 'community/:community_id/members', controller: :members

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :members
  has_many :users, through: :members
  has_many :ships
  has_many :sailings
  has_many :feeds

  def member?(user)
    return false if user.blank?
    members.where(user: user).present?
  end

  def add_member(user, type=:guest)
    return if member? user
    member = Member.new( user: user, type: type )
    members << member
    save
  end

  def page
    YAML.load page_data
  end

  def comments
    sailing_ids = sailings.collect {|s| s.id }
    Comment.where(sailing_id: sailing_ids).order(created_at: :desc)
  end

  def comment_rating_average
    rating_list = comments.map {|c| c.rating }
    return 4 if rating_list.empty?
    rating_list.inject(:+) / rating_list.length
  end

end

app/controllers/admin/communities_controller.rb
class Admin::CommunitiesController < Admin::ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to admin_community_path(@community), notice: 'コミュニティを作成しました' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to admin_community_path(@community), notice: '変更を保存しました' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to admin_communities_path, notice: 'コミュニティを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :page_data)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # 「興味あります」
  def interest
    # コメントをフィードとして保存
    feed_params = params.fetch(:feed, {}).permit(:body)
    feed = Feed.new({
      body: feed_params[:body],
      type: :interest,
      community: @community,
      user: current_user,
    })

    Slack.chat_postMessage(
      text: "#{current_user.name} さんが興味があると言っています\n#{community_url(@community)}\nメッセージ： #{feed_params[:body]}",
      username: "umineco app",
      channel: ENV['SLACK_NOTIFICATION_CHANNEL']
    )

    respond_to do |format|
      if feed.save
        # 参加者がまだコミュニティメンバーでなければ guest として追加する
        @community.add_member(current_user)
        format.html { redirect_to @community, notice: '興味がある旨を送信しました。' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # 「別日程なら参加したい」
  def another_time
    # コメントをフィードとして保存
    feed_params = params.fetch(:feed, {}).permit(:body)
    feed = Feed.new({
      body: feed_params[:body],
      type: :another_time,
      community: @community,
      user: current_user,
    })

    respond_to do |format|
      if feed.save
        # 参加者がまだコミュニティメンバーでなければ guest として追加する
        @community.add_member(current_user)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.slim
= form_for @community do |f|
  - if @community.errors.any?
    #error_explanation
      h2 = "#{pluralize(@community.errors.count, "error")} prohibited this community from being saved:"
      ul
        - @community.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/communities/edit.html.slim
h1 コミュニティを編集

== render 'form'

ul
  - @community.sailings.each do |sailing|
    - duration = tsrange2str sailing.duration
    li= link_to "#{duration[:date]} #{duration[:begin]} - #{duration[:end]}", edit_sailing_path(sailing)

p= link_to 'セーリングを追加', new_sailing_path
p= link_to 'コミュニティページを見る', @community
p= link_to 'コミュニティ一覧', communities_path

app/views/communities/index.html.slim
h1 コミュニティ一覧

ul
  - @communities.each do |community|
    li
      = link_to community.name, community
      = link_to '[Edit]', edit_community_path(community)
      = link_to '[Destroy]', community, data: { confirm: 'Are you sure?' }, method: :delete
      ul
        - community.sailings.each do |sailing|
          li
            = sailing.name

= link_to '[Create]', new_community_path

app/views/communities/new.html.slim
h1 New community

== render 'form'

= link_to 'Back', communities_path

app/views/communities/show.html.slim
- page = @community.page

- content_for :title do
  title= "#{page['meta']['title']} | umineco"
  meta itemprop="description" content=page['meta']['description']

- content_for :ogp do
  meta property='og:title' content="#{page['meta']['title']} | umineco"
  meta property="og:description" content=page['meta']['description']
  meta property="og:url" content="#{community_url(@community)}"
  meta property="og:image" content=page['meta']['image']

main
  article.l-inner.event

    // --------------event header
    .eventHeader
      h2.eventHeader__ttl= page['meta']['title']

      ul.eventHeader__info
        li
          span.icon-icn_yacht.icn_color-1
          = page['ship']['name']
        li
          span.icon-icn_map.icn_color-1
          = page['marina']['location']
        li
          a href="#reviewArea"
            span.icon-icn_review.icn_color-1
            = "レビュー#{@community.comments.length}件"

    .eventBody
      // --------------event main
      .eventBody__left
        #photoGallary
          .mainBox
            ul.main.isTransition
              - page['images'].each do |image|
                li.mainItem
                  = image_tag image, alt:""
            span.prev
              a href="#"
                span.icon-keyboard_arrow_left
            span.next
              a href="#"
                span.icon-keyboard_arrow_right

          .thumbnailsBox
            ul.thumbnails.isTransition
              - page['images'].each do |image|
                li.thumbnailsItem
                  .inner style="background-image: url(#{image})"
            span.prev
              a href="#"
                span.icon-keyboard_arrow_left
            span.next
              a href="#"
                span.icon-keyboard_arrow_right

        // --------------遊び方
        section.c-box
          h3.c-title-1
            = image_tag "community/ttl_community_1.png", alt:"遊び方"

          - page['points'].each.with_index(1) do |point, i|
            .c-box
              h4.c-title-2
                = image_tag "community/ttl_point_#{i}.png", alt:"Point#{i}"
                = point['title']
              - if point.key? 'image'
                .imgbox
                  = image_tag point['image'], alt:""
              - if point.key? 'youtube'
                .imgbox
                  iframe width="640" height="425" src="https://www.youtube.com/embed/#{point['youtube']}?rel=0" frameborder="0" allowfullscreen=true
              p.text
                = simple_format point['description']



        // --------------一日の流れ
        section.c-box
          h3.c-title-1
            =image_tag "community/ttl_community_7.png", alt:"一日の流れ"
          ul.oneDayFlow
            - page['schedules'].each do |schedule|
              li
                .oneDayFlow__img
                  =image_tag schedule['image'], alt:""
                .oneDayFlow__ttl
                  span= schedule['time']
                  = schedule['title']
                .oneDayFlow__text= schedule['description']



        // --------------私たちについて
        section.c-box
          h3.c-title-1
            =image_tag "community/ttl_community_3.png", alt:"私たちについて"

          .c-box
            .imgbox
              = image_tag page['about']['image'], alt:""
            .text= simple_format page['about']['description']

            // sns link
            .aboutClubSns
              - if page['about']['sns']['facebook'].present?
                .aboutClubSns__item
                  .c-btn.c-btn--Style1
                    a href=page['about']['sns']['facebook'] target="_blank"
                      = page['ship']['name']
                      | - Facebook

          .c-box
            h4.c-title-5
              .c-title-5__image
                = image_tag page['about']['captain']['image'], alt:""
              .c-title-5__name
                span 代  表
                = page['about']['captain']['name']
                - if page['about']['captain']['title'].present?
                  = "（#{page['about']['captain']['title']}）"
            .text= page['about']['captain']['introduction']

            // sns link
            - if page['about']['sns']['blog'].present?
              .aboutClubSns
                .aboutClubSns__item
                  .c-btn.c-btn--Style1
                    a href=page['about']['sns']['blog'] target="_blank" Blog

          // --------------ヨット情報
          .c-box
            h4.c-title-4
              |ヨット情報

            table.c-table
              tr
                th メーカー名
                td colspan="3"= page['ship']['maker']
              tr
                th メーカー種類
                td colspan="3"= page['ship']['product']
              tr
                th 全長
                td= page['ship']['length']
                th 定員
                td= page['ship']['capacity']
              tr
                th 出力
                td= page['ship']['power']
                th 推進力形式
                td= page['ship']['thrust']
              tr
                th 保管方法
                td= page['ship']['custody']
                th エンジン（モデル）
                td= page['ship']['engine']
              tr
                th 免許種別
                td= page['ship']['license']
                th 燃料種別
                td= page['ship']['fuel']

        // --------------連絡事項
        section.c-box
          h3.c-title-1
            =image_tag "community/ttl_community_4.png", alt:"連絡事項"

          h4.c-title-3 料金について

          table.c-table
            tr
              th 料金
              td= page['notice']['payment']['price']
            tr
              th お支払い方法
              td= page['notice']['payment']['method']
            tr
              th キャンセル期日
              td= page['notice']['payment']['cancel']

          h4.c-title-3
            |集合時刻・場所について

          table.c-table
            tr
              th 集合時刻
              td= page['notice']['gathering']['time']
            tr
              th 集合場所
              td
                = page['notice']['gathering']['place']
                .c-btn.c-btn--Style4
                  a href=page['notice']['gathering']['map'] target="_blank" MAP


          - if page['notice']['dissolution'].present?
            h4.c-title-3
              |解散時刻・場所について

            table.c-table
              - if page['notice']['dissolution']['time'].present?
                tr
                  th 解散時刻
                  td= page['notice']['dissolution']['time']
              - if page['notice']['dissolution']['place'].present?
                tr
                  th 解散場所
                  td
                    = page['notice']['dissolution']['place']

          .c-box
            h4.c-title-4
              |持ち物ついて
            ul
              - page['notice']['needs'].each do |need|
                li= need

          .c-box
            h4.c-title-4 備考
            p= simple_format page['notice']['note']

        // --------------レビュー
        section.c-box#reviewArea
          h3.c-title-1
            =image_tag "community/ttl_community_5.png", alt:"レビュー"

          .reviewStar
            span.number= "#{@community.comments.length}件"
            .starBig
              - average = @community.comment_rating_average.to_i + 1
              = image_tag "community/icn_star_#{average}.png", alt:"星#{average}"

          - @community.comments.first(3).each do |comment|
            .reviewBox
              .reviewBox__header
                .left
                  = image_tag comment.user.picture
                .right
                  .starSmall
                    = image_tag "community/icn_star_#{comment.rating + 1}.png", alt:"星#{comment.rating + 1}"
                  h4.ttl= comment.title

              .reviewBox__body
                p= simple_format comment.body

              p.reviewBox__info
                = comment.created_at.strftime("%Y年%m月")
                | /
                = comment.user.name

          .c-btn.c-btn--Style1
            a href="#" onClick="Modal.open('reviewList')"
              |他のレビューを見る

      // --------------event side
      .eventBody__right
        section#eventAction
          h2.c-title-4.reservationttl
            |日程・ご予約

          - @community.sailings.from_now.slice(0..2).each do |sailing|
            - duration = tsrange2str sailing.duration
            .reservationBox
              .reservationBox__left
                p.date= duration[:date]
                p.time
                  = duration[:begin]
                  | -
                  = duration[:end]

                - if current_user and sailing.participant? current_user
                  .c-btn.c-btn--Style2
                    | 仮予約済み
                - elsif sailing.participants.size >= sailing.capacity
                  .c-btn.c-btn--Style2
                    | 満員
                - else
                  .c-btn.c-btn--Style2
                    a.participateButton href="#" data-id=sailing.id
                      |一緒に遊ぶ
              .reservationBox__right
                p.ttl
                  |参加者
                p.participant
                  a href="#" onClick="Modal.open('participantList-#{sailing.id}')"
                    span.participant__number= sailing.participants.size
                    | /#{sailing.capacity}人


          // その他
          .consultationBox
            .c-btn.c-btn--Style1
              a href="#" onClick="Modal.open('anotherDateForm')"
                |別日程を確認する

            .c-btn.c-btn--Style1
              a.interestButton href="#"
                |興味あります

            .fbBtn
              .c-btn.c-btn--Style3
                a href="http://www.facebook.com/share.php?u=#{community_url(@community)}" onclick="window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;"
                  span.icon-icn_fb
                  |Facebookでシェアする

// ----------------------------------------------------------------以下modal

#ModalList style="display:none"

  - @community.sailings.from_now.each do |sailing|
    - duration = tsrange2str sailing.duration

    // --------------仮予約
    div id="reservationForm-#{sailing.id}" data-title="#{duration[:date]}に仮予約"
      p.message
        |送信ボタンを押していただくと、仮予約が完了します。
      //p.messageSmall
        |セーリングに参加することをあなたの友達にも知らせよう！
      = form_for :participant, url: participants_path(sailing_id: sailing.id) do |f|
        = f.hidden_field :share, value: 0
        //label.messageSmall
          = f.check_box :share, checked: true, class: :reservation_with_share
          | Facebookでシェアする
        //= f.text_area :share_body, value: "#{duration[:date]}のセーリングに参加します！"

        .c-btn.c-btn--Style2
          button type='submit' 送信

    // --------------参加者一覧
    div id="participantList-#{sailing.id}" data-title="#{duration[:date]}参加者一覧"
      ul.participantList
        - sailing.participants.each do |participant|
          - user = participant.user
          li
            .participantList__img= image_tag user.picture
            .participantList__name= user.name
      - if sailing.participants.size === 0
        | 参加者はまだいません。


  // --------------興味あります
  #interestForm data-title='興味あります'
    p.message
      |このヨットクラブに興味がある旨を伝えてよろしいですか？
    = form_tag interest_community_path(@community) do
      = text_area :feed, :body, placeholder: "伝えたい事があれば記入してください。"

      .c-btn.c-btn--Style2
        button type='submit' 送信

  // --------------別日程を確認する
  #anotherDateForm data-title='別日程を確認する'
    - @community.sailings.from_now.each do |sailing|
      - duration = tsrange2str sailing.duration
      .reservationBox
        .reservationBox__left
          p.date= duration[:date]
          p.time
            = duration[:begin]
            | -
            = duration[:end]

          - if current_user and sailing.participant? current_user
            .c-btn.c-btn--Style2
              | 仮予約済み
          - elsif sailing.participants.size >= sailing.capacity
            .c-btn.c-btn--Style2
              | 満員
          - else
            .c-btn.c-btn--Style2
              a href="#" onClick="Modal.open('reservationForm-#{sailing.id}')"
                |一緒に遊ぶ
        .reservationBox__right
          p.ttl
            |参加者
          p.participant
            a href="#" onClick="Modal.open('participantList-#{sailing.id}')"
              span.participant__number= sailing.participants.size
              | /#{sailing.capacity}人

  // --------------レビュー一覧
  #reviewList data-title='レビュー 一覧'
    .reviewStar
      span.number= "#{@community.comments.length}件"
      .starBig
        - average = @community.comment_rating_average.to_i + 1
        = image_tag "community/icn_star_#{average}.png", alt:"星#{average}"

    - @community.comments.each do |comment|
      .reviewBox
        .reviewBox__header
          .left
            = image_tag comment.user.picture
          .right
            .starSmall
              = image_tag "community/icn_star_#{comment.rating + 1}.png", alt:"星#{comment.rating + 1}"
            h4.ttl= comment.title

        .reviewBox__body
          p= simple_format comment.body

        p.reviewBox__info
          = comment.created_at.strftime("%Y年%m月")
          | /
          = comment.user.name

  // --------------送信しました
  #thanksMessage data-title='送信しました'
    p.message
      |ありがとうございました。
      br
      |オーナーからのご連絡をお待ち下さい。